#Desafio 009
print("\n Desafio 009")
number=int(input('Insira um número inteiro:'))
number1=int(number*1) #Neste caso, a tabuada é sempre a multiplicação dos decimais pelo número digitado, então é só repetição de código
number2=int(number*2)
number3=int(number*3)
number4=int(number*4)
number5=int(number*5)
number6=int(number*6)
number7=int(number*7)
number8=int(number*8)
number9=int(number*9)
number10=int(number*10)
print('A tabuada corresponde a {}x1:{}'.format(number,number1))
print('A tabuada corresponde a {}x2:{}'.format(number,number2))
print('A tabuada corresponde a {}x3:{}'.format(number,number3))
print('A tabuada corresponde a {}x4:{}'.format(number,number4))
print('A tabuada corresponde a {}x5:{}'.format(number,number5))
print('A tabuada corresponde a {}x6:{}'.format(number,number6))
print('A tabuada corresponde a {}x7:{}'.format(number,number7))
print('A tabuada corresponde a {}x8:{}'.format(number,number8))
print('A tabuada corresponde a {}x9:{}'.format(number,number9))
print('A tabuada corresponde a {}x10:{}'.format(number,number10))